### ISSUE TITLE
build errors after upgrade to 1.0.3

### ISSUE THREAD

**Issue by t-works** [finos/perspective#1646]
### Steps to Reproduce:
change perspective version from 1.0.1 to 1.0.3

### Expected Result:
build project

### Actual Result:
build errors:

 ERROR in ./node_modules/@finos/perspective-viewer/dist/pkg/perspective_viewer.js 1:0-90
Module not found: Error: Can't resolve './snippets/perspective-viewer-c0843f68e2505c94/inline0.js' in '[..]\node_modules\@finos\perspective-viewer\dist\pkg'
 @ ./node_modules/@finos/perspective-viewer/dist/esm/perspective-viewer.js 2:29690-29796 2:29925-29927
 @ ./src/index.tsx 14:0-35

ERROR in Conflict: Multiple assets emit different content to the same filename editor.worker.js.map

ERROR in Conflict: Multiple assets emit different content to the same filename editor.worker.js

ERROR in [..]\src\index.tsx
./src/index.tsx
[tsl] ERROR in [..]\src\index.tsx(19,70)
      TS2307: Cannot find module '@finos/perspective-viewer' or its corresponding type declarations.

ERROR in [..]\src\index.tsx
./src/index.tsx
[tsl] ERROR in [..]\src\index.tsx(47,12)
      TS2339: Property 'perspective-viewer' does not exist on type 'JSX.IntrinsicElements'.

ERROR in [..]\src\index.tsx
./src/index.tsx
[tsl] ERROR in [..]\src\index.tsx(47,72)
      TS2339: Property 'perspective-viewer' does not exist on type 'JSX.IntrinsicElements'.

### Environment:
windows 10
example repo: https://github.com/t-works/perspective1.0.3-react-error

**Comment by texodus** [comment]
Thanks for the report @t-works!  This is a bug introduced by our recent switch to `esbuild` as our packaging tool, which as I just now realized [does not support generating TS declaration files](https://esbuild.github.io/content-types/#no-type-system).  We'll get this fixed for the upcoming release, for now as a workaround you can 
* Use 1.0.0 (obviously ..) or
* `ts-ignore` these errors - they should _just_ be type errors, and I checked e.g. the built-in `react` example with `yarn start react`, which outputs the same errors but _does_ compile and work.

**Comment by t-works** [comment]
Thank you very much for your feedback! We are using the 1.0.1 for the time being. 
yep, we could TS ignore but this one:
Module not found: Error: Can't resolve './snippets/perspective-viewer-c0843f68e2505c94/inline0.js' in '[..]\node_modules@finos\perspective-viewer\dist\pkg'

does not allow us to build 1.0.3 - it is trying to find the file:
]\node_modules@finos\perspective-viewer\dist\pkg\snippets\perspective-viewer-c0843f68e2505c94/inline0.js
that doe snot exist.

Best 
Jerzy Kurowski

**Comment by texodus** [comment]
@t-works aha you are exactly right, good catch!  Verified this is [missing on `1.0.3`](https://www.jsdelivr.com/package/npm/@finos/perspective-viewer?path=dist%2Fpkg).

It appears that `wasm-pack` emits a `.gitignore` in this directory during compilation that overrides the `package.json` `"diles"` key, causing `./snippets/perspective-viewer-c0843f68e2505c94/` to not be packaged.

**Comment by timkpaine** [comment]
@t-works @texodus nice, I was just experiencing this same error

**Comment by texodus** [comment]
Both fixes are in the `1.0.4` release.
