### ISSUE TITLE
[Context Menu] "Export" and "Copy" items throw exception when selected

### ISSUE THREAD

**Issue by brianblakely** [finos/perspective#2455]
### Steps to Reproduce:
 1. Go to https://perspective.finos.org/block/?example=superstore
 2. Right-click one of the viewers
 3. Select either Export or Copy from the context menu

### Expected Result:
The respective commands should be executed

### Actual Result:
Throws exception `Uncaught (in promise) TypeError: l.unsafe_set_model is not a function`

### Environment:
Issue since at least 1.9.4. Confirmed working in 1.4.0.

**Comment by sinistersnare** [comment]
This is fixed in master, and will be included in the next release.
