### ISSUE TITLE
react example not working with version 0.9.0 

### ISSUE THREAD

**Issue by krzysztofpniak** [finos/perspective#1467]
### Steps to Reproduce:
download tag v0.9.0
run following:
`cd examples/react` 
`yarn && yarn start`

### Expected Result:
application will launch

### Actual Result:
$ webpack serve --open
[webpack-cli] Failed to load '/Users/krzysztofpniak/js/perspective/examples/react/webpack.config.js'
[webpack-cli] Error: Cannot find module '@finos/perspective/dist/esm/config'

### Environment:
macos big sur, nodejs 14

### Additional Context:
version v0.8.0 works
